### ISSUE TITLE
Aegir / Drupal 7 Views cant see wpplatform or wpsite

### ISSUE THREAD

**Issue by devekko** [mlutfy/hosting_wordpress#13]
1. need to update or create views and menu items to be non specific to Drupal or maybe create a Wordpress section

**Comment by devekko** [comment]
I tried to add wpplatform and wpsite as extra content items in the standard views but hit limits with the contrib code

**Comment by mlutfy** [comment]
This has been implemented (not 100%, but sort of usable) by the following commits (which I forgot to tag with this issue):

https://github.com/mlutfy/hosting_wordpress/commit/1d7087569d10dae5fc5d5f7ead038ea14009db85
https://github.com/mlutfy/hosting_wordpress/commit/c9d5d878e2848a3a9046b4f35fba4924396852a6
https://github.com/mlutfy/hosting_wordpress/commit/151d16b4827159a8fa34413cf0e9b0a0595cf939
https://github.com/mlutfy/hosting_wordpress/commit/f32385af4592507fae22d7230264627735bb8d31

It creates two new views for "WP Platforms" and "WP Site", since hosting_wordpress implements different entities (site vs wpsite).

**Comment by devekko** [comment]
this is all good, I want to do some Wordpress again and I absolutely do not want to do the WP Multisite thing... 

btw, hope to see you at http://aegircamp.org at UN maybe we can do a dedicated day just for Wordpress in Aegir a sprint or something

its an unconference this year
